from logging import exception
import psycopg2

try:
    conn = psycopg2.connect(database='wildlife', user='postgres', password='P@$$w0rd', host='localhost')
    print("opened database successfully")
except exception:
    print('database failure')

cur = conn.cursor()
cur.execute('SELECT ID,NAME,LIVES,WEIGHT,LEGS,CLASS,NUMBER,CATEGORY FROM CAGE')

rows = cur.fetchall()
while True:
    for row in rows:
        row = cur.fetchall()
        break
    print(row)


conn.commit()
conn.close()